package com.Lion.Rhino.Threa;

public class Sample {
    final static public String code[] = {
            "with Ada.Text_IO; use Ada.Text_IO;\nwith Ada.Integer_Text_IO; use Ada.Integer_Text_IO;\nprocedure main is\n    X: Natural := 10;\n    Y: Natural := 25;\n    Z: Natural := X + Y;\nbegin\n    Put(\"X + Y = \");\n    Put(Z);\nend main;",
            "#!/bin/bash\n\necho \"welcome to main\"",
            "x = 10;\ny = 25;\nz = x + y;\n\nprint \"Sum of \",x,\" and \",y,\" is \",z;\nquit;",
            ">+++++++++[<++++++++>-]<.>+++++++[<++++>-]<+.+++++++..+++.>>>++++++++[<++++>-]\n<.>>>++++++++++[<+++++++++>-]<---.<<<<.+++.------.--------.>>+.>++++++++++.",
            "#include<stdio.h>\n\nint main() {\n    int x=10;\n    int y=25;\n    int z=x+y;\n    printf(\"Sum of x+y = %i\", z);\n}",
            "#include<stdio.h>\n\nint main(void) {\n    int x=10;\n    int y=25;\n    int z=x+y;\n    printf(\"Sum of x+y = %i\", z);\n}",
            "(print  \"welcome to main\")",
            "(ns clojure.examples.hello\n(:gen-class))\n\n(defn sum-of-numbers [x y]\n(println (format \"x + y = %d\" (+ x y))))\n\n(sum-of-numbers 10 25)",
            "IDENTIFICATION DIVISION.\nPROGRAM-ID. HELLO-WORLD.\nDATA DIVISION.\n    WORKING-STORAGE SECTION.\n        77 X PIC 99.\n        77 Y PIC 99.\n        77 Z PIC 99.\nPROCEDURE DIVISION.\n    SET X TO 10.\n    SET Y TO 25.\n    ADD X Y GIVING Z.\n    DISPLAY \"X + Y = \"Z.\nSTOP RUN.\n",
            "x = 10\ny = 25\nz = x+y\n\nconsole.log(\"Sum of \", x , \" and \", y , \" is \", z)",
            "#include <iostream>\n\nusing namespace std;\n\nint main() {\n    int x=10;\n    int y=25;\n    int z=x+y;\n\n    cout<<\"Sum of x+y = \" << z;\n}",
            "#include <iostream>\n\nusing namespace std;\n\nint main() {\n    int x=10;\n    int y=25;\n    int z=x+y;\n\n    cout<<\"Sum of x+y = \" << z;\n}",
            "#include <iostream>\n\nusing namespace std;\n\nint main() {\n    int x=10;\n    int y=25;\n    int z=x+y;\n\n    cout<<\"Sum of x+y = \" << z;\n}",
            "using System;\n\nclass Program\n{\n    static void Main() {\n        int x = 10;\n        int y = 25;\n        int z = x + y;\n\n        Console.Write(\"Sum of x + y = \"+ z);\n    }\n}",
            "import std.stdio;\n\nvoid main(string[ ] args) {\n\n    int x = 10;\n    int y = 25;\n\n    int z = x + y;\n\n    writeln(\"x + y = \", z);\n}",
            "void main(){\n    var x = 10;\n    var y = 25;\n    var z = x + y;\n    print(\"x + y = $z\");\n}",
            "x = 10\ny = 25\nz = x + y\n\nIO.puts \"Sum of #{x} and #{y} is #{z}\"",
            //"io:format(\"Welcome to main!~n\").",
            "USE: io\n\n\"Hello, Welcome to main\" print",
            "> x = 10\n> y = 25\n> z = x + y\n> \"Sum of \",x ,\" and \", y,\" is \", z",
            "class HelloWorld\n{\n    static Void main()\n    {\n        x := 10\n        y := 25\n        z := x + y\n        echo(\"Sum of \" + x + \" and \" + y + \" is \" + z)\n    }\n}",
            ".( sum of 10 and 25 is ) 10 25 + .",
            "program sum\n    REAL X,Y,Z\n    X = 10\n    Y= 25\n    Z = X + Y\n    PRINT *,\"sum of x + y = \", Z\nend program sum",
            "Dim x as Integer = 10\nDIM y as Integer = 25\nDIM z as Integer\nz = x + y\n\nprint \"Sum of x + y = \"; z",
            "printf \"welcome to main\"",
            ".data\n.globl greet\ngreet:\n.string \"Welcome to main\"\n\n.text\n.global main\nmain:\n    pushq   %rbp\n    movq    %rsp,       %rbp\n    movq    $greet,     %rdi\n    call    puts\n    movq    $0,         %rax\n    leave\n    ret\n",
            "package main\n\nimport \"fmt\"\n\nfunc main() {\n    x:= 25\n    y:=10\n\n    z:= x + y\n\n    fmt.Printf(\"Sum of x + y = %d\", z)\n}",
            "def x = 10\ndef y = 25\n\nprint 'Sum of x + y = ' + (x + y)",
            "<?hh\n\n    $x=10;\n    $y=25;\n    $z=$x+$y;\n\n    $msg = 'Sum of x+y = ';\n\n    echo($msg.$z);",
            "addMe :: Integer -> Integer -> Integer\naddMe x y = x + y\n\nmain :: IO ()\nmain =  do\nputStr \"Sum of x + y = \"\nprint(addMe 10 25)",
            "procedure main()\n    x := 10;\n    y := 25;\n    z := x + y;\n\n    write (\"sum of \", x, \" and \",y,\" is \",z);\nend",
            "DO ,1 <- #19\nPLEASE DO ,1 SUB #1 <- #22\nDO ,1 SUB #2 <- #68\nDO ,1 SUB #3 <- #112\nDO ,1 SUB #4 <- #112\nDO ,1 SUB #5 <- #208\nDO ,1 SUB #6 <- #64\nDO ,1 SUB #7 <- #16\nPLEASE DO ,1 SUB #8 <- #162\nDO ,1 SUB #9 <- #214\nDO ,1 SUB #10 <- #56\nDO ,1 SUB #11 <- #242\nPLEASE DO ,1 SUB #12 <- #178\nDO ,1 SUB #13 <- #48\nDO ,1 SUB #14 <- #44\nDO ,1 SUB #15 <- #0\nDO ,1 SUB #16 <- #208\nDO ,1 SUB #17 <- #240\nDO ,1 SUB #18 <- #144\nDO ,1 SUB #19 <- #34\nPLEASE READ OUT ,1\nPLEASE GIVE UP\n",
            //"IDENTIFICATION DIVISION.\nPROGRAM-ID. MYPROGRAM.\nDATA DIVISION.\n    WORKING-STORAGE SECTION.\n        77 X PIC 99.\n        77 Y PIC 99.\n        77 Z PIC 99.\nPROCEDURE DIVISION.\n    SET X TO 10.\n    SET Y TO 25.\n    ADD X Y GIVING Z.\n    DISPLAY \"X + Y = \"Z.\nSTOP RUN.\n",
            //iscobal
            "public class MyClass {\n    public static void main(String args[]) {\n      int x=10;\n      int y=25;\n      int z=x+y;\n\n      System.out.println(\"Sum of x+y = \" + z);\n    }\n}",
            //"echo 'Welcome to main!'\nexit ''",jlang
            "fun main(args: Array<String>) {\n    val x: Int = 10\n    val y: Int = 25\n\n    val z = x + y\n\n    println(\"The sum of $x + $y is  $z\")\n}",
            "HAI 1.2\nVISIBLE \"Welcome to main!!\"\nKTHXBYE",
            "local x = 10\nlocal y = 25\nlocal z = x + y\n\nprint(\"Sum of x+y =\",z)",
            //"",mongodb
            "functor\nimport\n    System\n    Application\ndefine\n    {System.showInfo 'Welcome to main!'}\n    {Application.exit 0}\nend",
            //"",mysql
            "section .text\n\nglobal _start\n\n_start:\n\n    mov     eax, [x]\n    sub     eax, '0'\n    mov     ebx, [y]\n    sub     ebx, '0'\n    add     eax, ebx\n    add     eax, '0'\n\n    mov     [sum], eax\n\n    mov     ecx, msg\n    mov     edx, len\n    mov     ebx, 1\n    mov     eax, 4\n    int     0x80\n\n    mov     ecx, sum\n    mov     edx, 1\n    mov     ebx, 1\n    mov     eax, 4\n    int     0x80\n\n    mov     eax, 1\n    int     0x80\n\nsection .data\n    x db '5'\n    y db '3'\n    msg db  \"sum of x and y is \"\n    len equ $ - msg\n\nsegment .bss\n\n    sum resb 1\n",
            "class main\n{\n    static Main () : void\n    {\n        def x = 10;\n        def y = 25;\n        def z = x + y;\n        System.Console.WriteLine (\"Sum of {0} and {1} is {2}\", x, y, z);\n    }\n}",
            "var x,y,z :int\nx = 10\ny = 25\nz = x + y\necho (\"sum of \", x, \" and \", y, \" is \", z)\n",
            "var x = 10;\nvar y = 25;\nvar z = x + y;\n\nconsole.log(\"x + y = \" + z);",
            "#import <Foundation/Foundation.h>\n\nint main (int argc, const char * argv[])\n{\n    NSAutoreleasePool * pool = [[NSAutoreleasePool alloc] init];\n\n    int x = 10;\n    int y = 25;\n\n    NSLog(@\"Sum of x + y = %i\", (x+y));\n\n    [pool drain];\n    return 0;\n}",
            "print_string \"Welcome to OCAML online ide from com!\\n\";;",
            "vector = (1:1:10);\nmatrix = [vector ; vector * 5; vector * 10 ]\nmatrix(1:3, 2:4)",
            "Program AddNums(output);\n    var x,y,z:integer;\n    begin\n\n    x:=10;\n    y:=25;\n    z:=x+y;\n    writeln('The sum of x+y is ', z);\nend.",
            "$x = 10;\n$y = 25;\n$z = $x+$y;\n\nprint \"Sum of $x + $y = $z\";",
            "<?php\n\n    $x=10;\n    $y=25;\n    $z=$x+$y;\n\n    $msg = 'Sum of x+y = ';\n\n    print($msg.$z);\n\n?>",
            "\"Welcome to main\"\n(bye)",
            "int main()\n{\n    int x = 10;\n    int y = 25;\n    int z = x + y;\n    write(\"Sum of \" + x +\" and \" + y + \" is \" + z);\n    return 0;\n}",
            ":- initialization(main).\n  main :- write('Welcome to main!!').",
            "x=10;\ny=25;\nz=x+y;\n\nprint \"Sum of x+y =\", z;",
            "x=10;\ny=25;\nz=x+y;\n\nprint (\"sum of x+y =\", z);",
            "x <- 10\ny <- 25\nz <- sum(x,y)\n\ncat(\"x + y = \", z)",
            "(writeln \"Welcome to main!!\")",
            "var x = 10;\nvar y = 25;\nvar z = x + y;\n\nprint('Sum of ',x,' and ',y,' is ',z);",
            "x = 10;\ny = 25;\nz = x+y;\n\nprint \"Sum of x + y = \", z;",
            "fn main() {\n    let x = 10;\n    let y = 25;\n\n    let z = x + y;\n\n    println!(\"Sum of x and y = {} \",z);\n}",
            "\nobject MyClass {\n    def add(x:Int, y:Int) = x + y;\n\n    def main(args: Array[String]) {\n        print(\"sum of x + y = \" + add(25,10));\n    }\n}",
            "(define (sum a b)\n(display \"x + y = \")\n(display (+ a b)))\n\n(sum 10 25)\n(newline)",
            "Transcript show: 'Welcome to main'.",
            "var x = 10;\nvar y = 25;\nvar z = x + y;\n\nconsole.log(\"x + y = \" + z);",
            "\ncreate table calc(x int, y int);\n\ninsert into calc values(10, 25);\n\nselect x,y, (x+y) from calc;",
            "let x = 10\nlet y = 25\nprint(\"Sum of x and y = \", (x+y))",
            "set x 10\nset y 25\nset z [expr $x + $y]\n\nputs \"Sum of x +y =  $z\"",
            "`r``````````````````.W.e.l.c.o.m.e. .t.o. .J.D.o.o.d.l.ei",
            "Imports System\n\nPublic Class Test\n    Public Shared Sub Main()\n        Dim x, y as Integer\n        x = 10\n        y = 25\n        System.Console.WriteLine(\"Sum of x and y = \" & (x+y))\n    End Sub\nEnd Class",
            "module main;\n    initial begin\n        $display (\"Welcome to main!!!\");\n        $finish;\n    end\nendmodule",
            "Welcome to main   \n   \t  \t   \n\t\t    \t\n   \t\t  \t \t\n\t\t    \t \n   \t\t \t\t  \n\t\t    \t\t\n   \t\t \t\t  \n\t\t    \t  \n   \t\t \t\t\t\t\n\t\t    \t \t\n   \t \t\t  \n\t\t    \t\t \n   \t     \n\t\t    \t\t\t\n   \t\t\t \t\t\t\n\t\t    \t   \n   \t\t \t\t\t\t\n\t\t    \t  \t\n   \t\t\t  \t \n\t\t    \t \t \n   \t\t \t\t  \n\t\t    \t \t\t\n   \t\t  \t  \n\t\t    \t\t  \n   \t     \n\t\t    \t\t \t\n   \t\t \t\t\t\t\n\t\t    \t\t\t \n   \t\t  \t\t \n\t\t    \t\t\t\t\n   \t     \n\t\t    \t    \n   \t\t\t  \t\t\n\t\t    \t   \t\n   \t\t\t    \n\t\t    \t  \t \n   \t\t    \t\n\t\t    \t  \t\t\n   \t\t   \t\t\n\t\t    \t \t  \n   \t\t  \t \t\n\t\t    \t \t \t\n   \t\t\t  \t\t\n\t\t    \t \t\t \n   \t    \t\n\t\t    \t \t\t\t\n    \n\t\t     \n\n \t \t\t\t \t\t\t \t\t\t  \t  \t\t \t  \t \t\t\t \t   \t\t  \t \t\n\n \t \t\t \t\t\t  \t\t  \t \t \t\t\t \t\t\t \t\t \t\t   \t\t \t  \t \t\t \t\t\t  \t\t  \t \t\n\n\n\n\n   \t\t    \t \t\t  \t   \t\t  \t  \n\t   \n\t\n\n   \t\t\t \t\t\t \t\t\t  \t  \t\t \t  \t \t\t\t \t   \t\t  \t \t\n \n \t\t\t \n \n\t  \t\t\t \t\t\t \t\t\t  \t  \t\t \t  \t \t\t\t \t   \t\t  \t \t \t \t\t\t\t\t \t\t  \t \t \t\t \t\t\t  \t\t  \t  \n\t\n     \t\n\t   \n \n \t\t\t \t\t\t \t\t\t  \t  \t\t \t  \t \t\t\t \t   \t\t  \t \t\n\n   \t\t\t \t\t\t \t\t\t  \t  \t\t \t  \t \t\t\t \t   \t\t  \t \t \t \t\t\t\t\t \t\t  \t \t \t\t \t\t\t  \t\t  \t  \n \n\n \n\n\n\t\n\n   \t\t\t  \t  \t\t  \t \t \t\t    \t \t\t  \t  \n \n  \n \t\n\t \t\t\t \n    \t \t \n\t  \t\n\t  \t\t\t  \t  \t\t  \t \t \t\t    \t \t\t  \t   \t \t\t\t\t\t \t\t  \t \t \t\t \t\t\t  \t\t  \t  \n \n\n   \t\n\t   \n \n \t\t\t  \t  \t\t  \t \t \t\t    \t \t\t  \t  \n\n   \t\t\t  \t  \t\t  \t \t \t\t    \t \t\t  \t   \t \t\t\t\t\t \t\t  \t \t \t\t \t\t\t  \t\t  \t  \n \n\n   \t\n\t       \n\t\t \n\t\n\n   \t\t \t\t\t  \t\t  \t \t \t\t\t \t\t\t \t\t \t\t   \t\t \t  \t \t\t \t\t\t  \t\t  \t \t\n   \t \t \n   \t\t \t\n\t\n  \t\n  \n\t\n",
            "let x = 10\nlet y = 25\nlet z = x + y\n\nprint \"sum of x + y = \", z",""
    };
}
